version: "3"
services:
  jupyter-notebook:
    image: jupyter/minimal-notebook:latest
    ports:
      - "8888:8888"  
    volumes:
      - "/home/jeffrey/docker-volumes/rtde-dev/jupyter-notebook:/home/jovyan/work"
    networks:
      - rtde-dev-network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    ports:
      - "9200:9200"
    volumes:
      - "/home/jeffrey/docker-volumes/rtde-dev/elasticsearch-data:/usr/share/elasticsearch/data"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - rtde-dev-network
    ulimits:
      memlock:
        soft: -1
        hard: -1
networks:
  rtde-dev-network:

