version: "3"
services:
  jupyter-notebook:
    image: jupyter/datascience-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - "./work-volume:/home/jovyan/work"
    command: start-notebook.sh --NotebookApp.token=''
